### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by jtannas** [bensheldon/good_job#1074]
Hello,
We recently had some OOM errors in our system.
Looking back on our metrics, it seems like the GoodJob runners have a significant memory leak.
Here's a graph of the memory usage over the last few months, with each of the dropoffs corresponding to deploying a new version of our application.
![image](https://github.com/bensheldon/good_job/assets/22785056/3fdf2cfa-54c4-43a8-bfc6-b6482fdf4bd4)

The leak rate appears to be ~150MB per day.
Thoughts?

**Comment by bensheldon** [comment]
That looks bad! 😬  ...but I don't imagine that it's specifically GoodJob; I haven't experienced that or seen it reported before (though someone does have to be first).

I'm imagining that the cause is one or more of your application's jobs that are allocating/retaining objects, and not specifically the GoodJob framework. 

My recommendation would be to do some memory profiling around jobs. There's a lot of resources on using tools like MemoryProfiler or DerailedBenchmarks to profile them. Here's an example: https://blog.appsignal.com/2022/08/10/a-deep-dive-into-memory-leaks-in-ruby.html

**Comment by jtannas** [comment]
Will do :)
I assumed it was Goodjob due to not seeing the same pattern in our API, but I'll work on narrowing it down to something specific since no else is reporting the issue.

**Comment by mengqing** [comment]
Hi @jtannas, just wondering if you have found anything that might have caused the memory leak? I, too is having memory leak issue and is having difficulty tracking it down
