### ISSUE TITLE
Default concurrency key

### ISSUE THREAD

**Issue by bforma** [bensheldon/good_job#1110]
First off, great job on creating the GoodJob gem!

I'm using the latest version of GoodJob (3.19).

I've noticed that when I use the following config for concurrency controls, no controls are applied, because the concurrency key becomes `nil`:

```ruby
Class MyJob < ApplicationJob
  good_job_control_concurrency_with(
    total_limit: 1,
  )

  def perform
    # perform job
  end
end
```

The following will enqueue two jobs (when no workers are running in any form):

```ruby
MyJob.perform_later
MyJob.perform_later
```

However, when I change the concurrency control config (by providing a key generator) with the following, only a single job is enqueued (as I would expect):

```ruby
good_job_control_concurrency_with(
  total_limit: 1,
  key: "MyJob-#{arguments.first}"
)
```

Am I missing something? I find this (default) behavior confusing, and would expect a default concurrency key being generated, when none is supplied. Correct me if I'm wrong, but I can't find anything about this in the docs as well.

I would expect something like this as a default (class name + serialized arguments as concurrency key):

```ruby
-> { "#{self.class.name}-#{ActiveJob::Arguments.serialize(arguments)}" }
```

Thanks!

**Comment by bensheldon** [comment]
Good flag, there is not a default concurrency key assigned: 

https://github.com/bensheldon/good_job/blob/eb654635df314f2540382fee823c655b2a1f6655/lib/good_job/active_job_extensions/concurrency.rb#L92-L106

I imagine I deferred this because I couldn't think of a good default: should it be the classname (because it's defined on a class)... but what about when it's defined in ApplicationJob. Should it include arguments? Those can be high cardinality.

I think the simplest path here would be to call out in the Readme that a key must be provided.

**Comment by bforma** [comment]
I agree that setting a good default is hard. Adding advice about this in the documentation would be helpful 👍 .

Besides that I would still expect the following configuration to issue an error (or warning?), simply because no concurrency limits are applied:

```
good_job_control_concurrency_with(
  total_limit: 1,
)
```

**Comment by Earlopain** [comment]
In #1145 the job class was made the default concurrency key, the docs at https://github.com/bensheldon/good_job?tab=readme-ov-file#concurrency-controls also have been expanded on a bit.

I believe this can be closed now (I totally forgot to link to this issue in the PR 🤦)
