### ISSUE TITLE
Processes are created for puma workers after version v3.12.5 with execution_mode==:external

### ISSUE THREAD

**Issue by finalarena** [bensheldon/good_job#1156]
Processes are created for puma workers (cluster mode) - after version v3.12.5. 

![image](https://github.com/bensheldon/good_job/assets/235729/7ccc6439-571d-4237-8398-b187bf8461e4)

Count of processes created = count of puma workers. And none are created if puma run in non-cluster mode.

This issue exists in 3.12.6 as well as 3.21.1. Downgrading to v3.12.5 fixes it again.

The net effect for me on heroku is the web dyno(s) get swamped. I have separate processes, and the following example in :external execution mode will result in 2 good_job processes.
```
web: bundle exec puma -C config/puma.rb
worker_goodjobs_high_priority: bundle exec good_job start --queues="+high_priority,orders,kittenpics"
```

puma.rb includes:

```
on_worker_boot do
  ActiveRecord::Base.establish_connection if defined?(ActiveRecord)
  GoodJob.restart
end

before_fork do
  GoodJob.shutdown
end

on_worker_shutdown do
  GoodJob.shutdown
end

MAIN_PID = Process.pid
at_exit do
  GoodJob.shutdown if Process.pid == MAIN_PID
end
```

![image](https://github.com/bensheldon/good_job/assets/235729/ffc52068-8c16-47df-af6c-7f285495fda9)

**Comment by bensheldon** [comment]
Thanks for opening the issue! I think I understand what's going on here. There was a significant refactor in 3.12.6: #861 

Simply, you shouldn't be calling `GoodJob.restart` if you don't want to run GoodJob in that process. So my recommendation would be to remove all of that configuration from your `config/puma.rb` file, if you're running the `$ good_job` CLI separately.

(unrelated, but btw, you almost never want `ActiveRecord::Base.establish_connection if defined?(ActiveRecord)` in any Rails 6+ app because it will leak a database connection unnecessarily)

The fuller explanation: that refactor (#861) made a clearer distinction between:

- `execution_mode:` meaning "how should a job be executed after it is enqueued?" which becomes a responsibility of the Active Job Adapter for where to send the job on enqueue. 
- The GoodJob part that executes/performs the jobs (the "Capsule") which is controlled by `restart` and `shutdown`.

Those two concepts were previously commingled together.

**Comment by bensheldon** [comment]
No prob! I appreciate that you opened an issue; anyone else experiencing this may also search and find it too 🤗
