### ISSUE TITLE
Clarify required async mode DB pool size

### ISSUE THREAD

**Issue by yenshirak** [bensheldon/good_job#1209]
In the `Database connections` section there's the following about the async mode:

> When GoodJob runs in :async mode (in Rails's development environment, by default), the following database pool configuration works, where:
> 
> ENV.fetch("RAILS_MAX_THREADS", 5) is the number of threads used by the web server
> 1 is the number of connections used by the job listener
> 2 is the number of connections used by the cron scheduler and executor
> ENV.fetch("GOOD_JOB_MAX_THREADS", 5) is the number of threads used to perform jobs
> # config/database.yml
> 
> pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + 1 + 2 + ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i %>

Below that in the `Execute jobs async / in-process` section there's the following:

> Ensure that you have enough database connections for both web and job execution threads:
> 
> # config/database.yml
> pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5).to_i + ENV.fetch("GOOD_JOB_MAX_THREADS", 4).to_i %>
> 

If both are about the async mode DB pool size then one of them seems wrong.
Shouldn't the second one be `ENV.fetch("RAILS_MAX_THREADS", 5).to_i + 1 + 2 + ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i` as well?

**Comment by bensheldon** [comment]
Yep, those are inconsistent. The simplest and most up-to-date correction would be `2 + ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i`

That's also a little misleading because `GOOD_JOB_MAX_THREADS` isn't the total upperbound of threads, but more like "the default number of threads for a a configured pool" i.e. if you're using multiple pools (like `default;other` with the semicolon) that will be `GOOD_JOB_MAX_THREADS * number-of-pools`.

There's now a calculator: https://github.com/bensheldon/good_job/blob/988665ee849c914a6e8edb4afb45e4bc8383203b/lib/good_job/configuration.rb#L50-L53

Lastly, it's really not necessary to be precise with this number so long as the the number is larger than the maximum total threads. It would be safest to simply set this to `50` and not worry about it; the Active Record Database Connection Pool will never allocate more connections than it strictly needs. (I've heard rumors that Rails might even remove the `pool` size in the future because it's not very useful to configure)

**Comment by yenshirak** [comment]
Thanks for the clarification.
