### ISSUE TITLE
Production worker doesn't show any processes

### ISSUE THREAD

**Issue by nathanpalmer** [bensheldon/good_job#1214]
I'm noticing two strange things in production, I'm wondering if there is a bug or if I have something misconfigured.

1. The Good Job Dashboard says there are no processes running. Despite there being a worker active.
2. Logs constantly say: `WARNING:  you don't own a lock of type ExclusiveLock`

I'm running cron and read through a related ticket of #388 but didn't find a solution in there. My production instance is simply executing `bin/bundle exec good_job start`. It's running against a PostgreSQL 15 server. Thoughts?

*FYI, I've started using good_job recently instead of sidekiq, so far I've loved much of this! Really glad to see a good postgres solution out there. (I previously used Que as well, and this is even better)

**Comment by bensheldon** [comment]
That's strange! Thanks for opening an issue. Just thinking through the pieces here:

- The `WARNING:  you don't own a lock of type ExclusiveLock` happens when Postgres tries to _unlock_ an advisory lock that the current database connection has not locked (either the lock doesn't exist _anywhere_ or the current connection wasn't the locker)
- If you're not seeing any Processes listed in the Dashboard, and you're seeing that warning frequently in the logs, I'm imagining that the Process itself is failing to acquire an advisory lock when it is ["registered"](https://github.com/bensheldon/good_job/blob/988665ee849c914a6e8edb4afb45e4bc8383203b/app/models/good_job/process.rb#L86-L93) inside [of the Notifier](https://github.com/bensheldon/good_job/blob/main/lib/good_job/notifier/process_heartbeat.rb), and then it's erroring and trying to release the lock it couldn't acquire in the first place. That will loop.

So I'm imagining the reason being something like: Maybe GoodJob has been connected to a readonly replica database, or a database that isn't able to create records, or advisory locks, or maybe the schema hasn't been updated with the proper tables. 

If you have production console access (`bin/rails c`) you could try running `GoodJob::Process.register` manually in the console  to see if you can simulate a more meaningful error.

**Comment by nathanpalmer** [comment]
Thanks for the response! We do have a readonly replica. I had disabled it around 12:00PM, so it's been turned off for the last hour. I'm actually seeing processes now in the UI and manually calling `GoodJob::Process.register` works fine in the console too.

However, I'm still getting the `WARNING:  you don't own a lock of type ExclusiveLock` messages. The most recent one was 5 minutes ago. 

I just moved one of our cron tasks over to a different scheduler since we're getting them executed 2 or 3 times every time they should perform and that's causing some chaos. I'm unsure if it's related to this or not.

**Comment by bensheldon** [comment]
That does sound healthier! 🙌

I'm not sure what might be causing the sporadic warnings. You wouldn't happen to be using PgBouncer or something that might be multiplexing connections?

**Comment by nathanpalmer** [comment]
Yes.... yes I do happen to be using PgBouncer. I could probably disable it for the worker though if that might be causing an issue.

**Comment by bensheldon** [comment]
Aha. Yes, PgBouncer can be a problem: https://github.com/bensheldon/good_job#pgbouncer-compatibility

**Comment by nathanpalmer** [comment]
Alright! Well... I missed that. I'm using environment variables so I'll just use a different variable for the worker than I do for web. I have to do this anyway for the `db:migrate` jobs. But it sounds like this might solve my problems! I appreciate it!

**Comment by bensheldon** [comment]
Yay! Glad we could get this figured out 🙌🏻

**Comment by ruslankhaertdinov** [comment]
He there!
This also was issue for me, thanks for your point about pgbouncer.
