### ISSUE TITLE
PG Good Job rows add up

### ISSUE THREAD

**Issue by resistorsoftware** [bensheldon/good_job#1262]
I notice that my Heroku Good Job queue is chewing through 800 jobs per day. I added the engine to view the dashboard and it confirms the 800 jobs per day are succeeding, something I validated looking through my logs. That being said, I notice two tables in my Good Job DB are acquiring rows, at a pace of 1600 per day, so 800 on Good Jobs table and 800 more in Good Job Executions. 

So, these 1600 rows per day? What am I collecting these for? Is that correct behaviour? Should I run my own little rake task to delete these rows? I am curious. This is my first use of Good Job, coming from Redis backed Sidekiq so I am a little out of touch with what is going on under the hood. Any insights? Can someone kindly let me know that this is normal and we get used to it? Or that I am doing something dumb. 

I naively figured any Job done, would just be gone!

**Comment by bensheldon** [comment]
Yep, that sounds like GoodJob is working correctly. GoodJob keeps those records so that it has a record of every execution of every job you've run. When everything is running ok, the value there largely just to verify everything is working correctly (or doublecheck latencies). And when a job is broken, it's helpful to see every time the job was run, all of the errors, and when it was retried.

Also totally agree that the rows can add up if you're trying to fit your app within Heroku's cheapest database with a 10k row limit.

This is the configuration you can adjust for your needs: https://github.com/bensheldon/good_job?tab=readme-ov-file#monitor-and-preserve-worked-jobs

**Comment by resistorsoftware** [comment]
Thanks for the comments. I guess was screws me up was running the clean up tasks.. and seeing no change. I will play around more though!

With 1876 rows in Good Job tables... 
```
heroku run bundle exec good_job cleanup_preserved_jobs
Running bundle exec good_job cleanup_preserved_jobs on ⬢ yodler... up, run.9110 (Basic)
I, [2024-02-23T01:29:02.257317 #2]  INFO -- : [GoodJob] GoodJob destroyed 0 preserved job execution records finished before 2024-02-09 01:29:02 UTC.
```
So why were zero jobs destroyed? What am I doing wrong here? Is it all predicated on the config parameter of preserve_job_records? I will set that to false and see what happens with this task.

**Comment by resistorsoftware** [comment]
Never mind! I added in the --before-seconds-ago and it worked. I assumed with no parameter for that it would just nuke everything. Sorry for that! I will look into the code more too to teach myself better. 

Thanks so much for this gem!
