### ISSUE TITLE
ActiveSupport::CurrentAttributes reset after `perform_later`

### ISSUE THREAD

**Issue by AlfonsoUceda** [bensheldon/good_job#1320]
Hi!

Would like to know if this is a bug in active job or good job but I have a simple scenario failing in dev mode:
```ruby
Current.foo_id = SecureRandom.uuid

MyJob.perform_later

Current.foo_id # => nil
```
I was expecting to get the uuid but it gets reset.

This is my config for dev mode:
```ruby
config.active_job.queue_adapter = :good_job
config.good_job.execution_mode = :external
```

I've read that for tests using inline is intentional but for dev mode with this settings is weird, is that a bug?

**Comment by bensheldon** [comment]
I've always treated it as an edge-case, but I went to see how Active Job handles it and maybe it would be a rather simple change to isolate inline jobs in their own thread: https://github.com/rails/rails/pull/37568

**Comment by bensheldon** [comment]
I re-familiarized myself with this. What you're seeing is expected, and that's because Active Job itself wraps job execution with a Rails Executor, and a Rails Executor will reset CurrentAttributes when it exits. Every web request gets wrapped automatically with a Rails Executor, which makes the job's Executor a no-oop (doubly wrapped Executors are ignored) and the reset happens when the outermost Executor exits. 

But in your example, I imagine you're running that in the console, which I don't think is wrapped with a Rails Executor, which make's Active Job's Rails Executor perform a reset.

I wrote about this a bit here: https://island94.org/2023/11/rails-executor-increasingly-everywhere
