### ISSUE TITLE
ActiveSupport::CurrentAttributes Compatibility

### ISSUE THREAD

**Issue by JonathanFrias** [bensheldon/good_job#1341]
I have an interesting bug report for you.

Let's say you use `ActiveSupport::CurrentAttributes`:

```ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end
```

And you want to use it with GoodJob:

```ruby
class MyGoodJob < ApplicationJob
  def perform(user_id)
    Current.user = User.find(id)
    # .. some work
    GoodJob::Batch.enqueue do
       MyGoodJob.perform_later(Current.user.manager_id) # raises error
       # Current.user # => nil here
    end
  end
end
```

I looked into this and the reason is the good job calls the function `Rails.application.executor.wrap` twice in this code which does work to ensure isolated execution state. Part of that work includes calling `reset` on all descendants of `ActiveSupport::CurrentAttributes`. This resets all of the attributes.

I'm not sure if this is an issue or expected behavior. I think it should at least be documented. This is the workaround I've come up with so far

```ruby
class Current < ActiveSupport::CurrentAttributes
  attribute :user, :_locked_attributes
  def locked_attributes
    Current._locked_attributes = true
    yield
    Current._locked_attributes = nil
  end

  def reset
    return if Current._locked_attributes
    super
  end
end
```

Thanks for your again for your work on this project! @bensheldon

**Comment by Earlopain** [comment]
This is a bug in rails: https://github.com/rails/rails/issues/49227, there's also a bit more info at https://github.com/bensheldon/good_job/issues/1320 and its linked issues/prs/blogpost.

I agree it's very unexpected.

**Comment by bensheldon** [comment]
That's the correct issue @Earlopain that explains the problem. Thank you!

In this example, it's somewhat worse because `Batch.enqueue` also has its own `Rails.application.executor.wrap` because it takes an advisory lock when enqueuing and thus requires a wrapping executor to ensure the connection is persisted:

https://github.com/bensheldon/good_job/blob/fbd1a5b730bd735110eb23e7be72f61128f346a2/app/models/good_job/batch.rb#L104-L105

Is this example code you're running in a test or console and is there an active Rails executor? (`puts Rails.application.executor.active?`). The underlying solution is to _always_ have a wrapping Rails executor, which usually is the case in a real request or Active Job perform. 

Rails now wraps all test cases with an executor (though I think you must opt in). RSpec has not done so yet, though there are workarounds: https://github.com/rspec/rspec-rails/issues/2713

**Background:**
- When an executor is entered for the first time, it [resets CurrentAttributes](https://github.com/rails/rails/blob/4bb73233413f30fd7217bd7f08af44963f5832b1/activesupport/lib/active_support/railtie.rb#L49-L49)
- Any subsequent times an `executor.wrap` is called inside an executor, it [is a noop](https://github.com/rails/rails/blob/4bb73233413f30fd7217bd7f08af44963f5832b1/activesupport/lib/active_support/execution_wrapper.rb#L87-L87).

**Comment by JonathanFrias** [comment]
Okay that makes sense. Yes, I was running it directly in the console to test the job. Perhaps console sessions should also be wrapped with `Rails.application.executor.wrap`.

Consider the example:

```ruby
rails console

# Fail
Current.user = User.find(id)
MyGoodJob.new.perform(...)

# Success
Rails.application.executor.wrap do
  Current.user = User.find(id)
  MyGoodJob.new.perform(...) 
end
```

**Comment by JonathanFrias** [comment]
Closing this as I'm finding many other discussions about this elsewhere
