### ISSUE TITLE
Unable to use labels with kwargs in job initializer 

### ISSUE THREAD

**Issue by gap777** [bensheldon/good_job#1350]
Hi,
Just trying out labels, and it appears that if I have kwargs in the initializer of my jobs, I can't use labels.

My job:

```
class TestJob < ApplicationJob
    include GoodJob::ActiveJobExtensions::Concurrency
    include GoodJob::ActiveJobExtensions::Labels

  def perform(kwarg1:, kwarg2:)
     good_job_labels << did_the_thing? ? 'Foo' : 'Bar'
  end

```

 I get this in the error logs:

```
wrong number of arguments (given 1, expected 0; required keywords: kwarg1, kwarg2)
```

**Comment by bensheldon** [comment]
This is an Active Job thing: `ActiveJob::Base#initialize` should never have its method signature changed. I think you mean to customize the `#perform` signature to pass parameters to a job.

**Comment by gap777** [comment]
@bensheldon 🤦  I created that example for this, trying to reproduce a more complicated example in my codebase. I don't have that obvious mistake in the real thing. ;-)

But still... I'm seeing that error about wrong number of arguments for perform when I add in the labels mixin.
Can you try that on your end, with a perform having kwargs and the label mixin present?

**Comment by bensheldon** [comment]
@gap777 sorry, I missed the reply. Can you share the code (both your job and the calling code) that you're using?

**Comment by ElMassimo** [comment]
@bensheldon I believe that the missing piece is that when overriding the `initialize` method in the `GoodJob::ActiveJobExtensions::Labels` module, it should use [`ruby2_keywords(:initialize)`](https://github.com/rails/rails/blob/main/activejob/lib/active_job/core.rb#L103), otherwise by the time the arguments reach `activejob`, the information about whether the arguments were kwargs or not has been lost.

I'll make a PR.
