### ISSUE TITLE
Question: is it possible to clean a set of scheduled jobs (by class name) from console?

### ISSUE THREAD

**Issue by blocknotes** [bensheldon/good_job#1410]
Hey :)
Thank you for the nice gem!

I'm in this situation: in our project we renamed a job class name without considering that a good number of jobs with the old class name were already scheduled... thousands of jobs 😄 

I saw that I can discard/destroy from the UI but it's useful for a small number of jobs.
So I wonder if it's feasible to do the same via console, specifying the job class name.

**Comment by janWITZANY** [comment]
Hi :) 

You should be able to destroy already discarded jobs (or discard unfinished jobs) like this:

```ruby
GoodJob::Job.where(job_class: "ClassNameOfJob").discarded.each(&:destroy_job)
```

**Comment by bensheldon** [comment]
Yep, @janWITZANY is exactly correct 👍 You could also rename all of the job's to have the new job class:

```ruby
GoodJob::Job.where(job_class: "OldJobClass").update_all(job_class: "NewJobClass")
```

`GoodJob::Job` is plain old Active Record model. I discourage folks from calling it in their application long term (because I consider it a private API and it might change), but for 1-off maintenance tasks like this, go for it.

**Comment by janWITZANY** [comment]
Thanks for the clarification, @bensheldon.

I am curious, and that's the actual reason I was looking into the issues: how would you delete or discard jobs in production?

I am a bit confused because the guide to upgrading from v3 to v4 mentions "Enqueues and executes jobs via the GoodJob::Job model instead of GoodJob::Execution." So, I thought this would also apply to dequeuing jobs.

**Comment by bensheldon** [comment]
> how would you delete or discard jobs in production?

There isn't a public API for that. I haven't heard from anyone who isn't doing a 1-off maintenance task like you are, which usually involves a unique situation (and thus scope / query). Which is why I suggest to just use the models with the caveat not to build that permanently into your app because it might change. 

If you have a user story like "As a user of the application, I want to be able to trigger a _task_ that might take a while, but I also want to be able to cancel it if I no longer need it" then you should build a `Task` model into your application with a `Task.canceled_at` column and if you put it in a background job do like:

```ruby
def perform(task)
  return if task.canceled_at.present?
  # ...
  task.make_finished
end
```

Essentially: the background jobs queue is an operational internal implementation detail; if you need to manage lifecycle of something in your application, do that separately _in your application_.

**Comment by blocknotes** [comment]
> Yep, @janWITZANY is exactly correct 👍 You could also rename all of the job's to have the new job class:
> 
> ```ruby
> GoodJob::Job.where(job_class: "OldJobClass").update_all(job_class: "NewJobClass")
> ```
> 
> `GoodJob::Job` is plain old Active Record model. I discourage folks from calling it in their application long term (because I consider it a private API and it might change), but for 1-off maintenance tasks like this, go for it.

Thank you @janWITZANY & @bensheldon - sounds good to me - feel free to close the issue if you want 👍

**Comment by blocknotes** [comment]
Another question... 😁 
I decided to rename the class name of the "old jobs" using the new class - good.
When in the UI I look for the old class name (in Scheduled tab) I get the jobs with the new class as results.
Does this mean that the old class name is stored somewhere else? Is there some kind of cache? Am I missing something else?

**Comment by blocknotes** [comment]
Don't worry - I did something similar just to be sure:

```rb
GoodJob::Job.where(job_class: "NewJobClass").find_each do |job| 
  job.job_class = "NewJobClass"
  job.serialized_params["job_class"] = "NewJobClass"
  job.save(validate: false)
end
```

And in the UI now I find only the new class name jobs.
I think we are done 👍
