### ISSUE TITLE
Batch callback job not enqueued after success of retried job

### ISSUE THREAD

**Issue by bavani69** [bensheldon/good_job#1450]
Hi Ben,
Great work on GoodJob V4. We have yet to upgrade, but looking forward to using Ordered Queues and Throttling features.

Current good_job version: 3.17
Rails: 7.0

We've been using Batches for a while, and I observed a strange issue. Here's what the code looks like:
```
def perform(batch, params):
    stage = batch.properties[:stage]
    ...
    if stage.nil?
        GoodJob::Batch.enqueue(on_success: ThisCallbackJob, stage: 1) do
            # perform a bunch of jobs
        end
    elsif stage == 1
        # perform another job
    end
end
```
The Callback job is enqueued with stage: 1 when the bunch of jobs succeed, and it is not enqueued when it fails. But when we fix the issue with our data and retry the failed job, it does not proceed to enqueue the Callback job. Am I misunderstanding what `on_success` is supposed to do?
Moreover, the callback job shows up as succeeded, so we cannot retry that to resume it. How can I turn its state to `:discarded`, so that we could retry the callback job when one of the jobs fail?

**Comment by bensheldon** [comment]
I'm glad you opened this issue! If I'm understanding the situation correctly, the current behavior of batches is ill-defined when:

_A batch has a job that's been discarded [which fires off the discarded batch callback, and potentially the finished] and then the job is (manually) retried and the job completes successfully._ 

The options that come to mind here are:

- Anytime a job that is part of a batch is unfinished (I consider a job discard a "final" state, even though it is possible to undo that by retrying through the dashboard) the batch is reenqueued. Reenqueuing the batch would mean that all callbacks (discard, success, finish) would be re-invoked when that job finishes.
- Add the option for batch callbacks of a finished batch to be manually re-invoked from the Dashboard based on the state of the current jobs.
- Something more complicated....

I sort of lean towards allowing the batch itself be "retried" which would clear the finished state, and retry any discarded jobs. I think a batch retry could take place if the batch is in a finished-but-discarded state, which would also be ok if someone had separately retried individual jobs within the batch because that would just kick off the callbacks if all the jobs are finished. Hmmm.

Does that make sense?

**Comment by bavani69** [comment]
Yeah, makes sense and sounds intuitive as well. 
But retrying a batch job comes with one caveat - the jobs within the batch have to be idempotent. If not, like sending mails to customers with jobs instantiated in a loop, some of those emails would be sent again.
This situation can easily be handled though.
