### ISSUE TITLE
Configuring connection pool in external mode

### ISSUE THREAD

**Issue by olivier-thatch** [bensheldon/good_job#1483]
Hello,

The README says the following:
> When GoodJob runs in :external mode (in Rails' production environment, by default), the following database pool configurations work for web servers and worker processes, respectively.
>
> ```yaml
> # config/database.yml
>
> pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
> ```
>
> ```yaml
> # config/database.yml
> 
> pool: <%= 1 + 2 + ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i %>
> ```

This is probably a naive question, but... how are we supposed to use different `pool` values for Rails and GoodJob if they read from the same `config/database.yml` and share the same environment?

I can think of workarounds, e.g. something like this:
```yaml
pool: <%= ENV["GOOD_JOB_MAX_THREADS"] ? (1 + 2 + ENV.fetch("GOOD_JOB_MAX_THREADS", 5).to_i) : ENV.fetch("RAILS_MAX_THREADS", 5).to_i %>
```
and then ensure that `GOOD_JOB_MAX_THREADS` is only set for the GoodJob service and not the Rails one, but if that's the way to go the documentation should probably reflect that. Am I missing something?

**Comment by bensheldon** [comment]
Thanks for asking! I should do a more opinionated pass on the Readme, because I think it makes it way too complicated. 

My recommendation this: Don't set a minimum but rather just set like `50` or `100` and don't worry about it from the perspective of the application. You'll need to have those connections available from the database, but trying to set a minimum in the database.yml isn't necessary and can lead to not having enough database connections available.

You can only ever have too few database connections; Active Record will never provision _more_ database connections than will be used. And the way to reduce database connections is by configuring the level of concurrency (puma threads, load_async threads, good_job threads, etc.) _not_ the database pool size.

**Comment by olivier-thatch** [comment]
Thanks for the reply! Just to make sure I understand correctly:
* ActiveRecord will never create more than 1 connection per thread
* the default pool size for a Rails app is set to `RAILS_MAX_THREADS`, which is the number of threads used by each Puma process running the Rails app
* for GoodJob, the total number of threads is the number of worker threads (set via `GOOD_JOB_MAX_THREADS`), plus an additional 3 threads internal to GoodJob (job listener / cron manager)
* your advice is that while the pool size should _at a minimum_ be set to the maximum number of threads (that need to run ActiveRecord queries), there is no downside to setting it a higher value, therefore one might as well set it to `50` or `100` and call it a day

Is that correct? If so that makes sense to me. I guess the worst that could happen is that you end up establishing more connections than the database server can handle, but then as you said the proper way to fix that is to reduce the number of threads establishing connections rather than arbitrarily limiting the pool size.

**Comment by olivier-thatch** [comment]
My colleague just pointed me to https://island94.org/2024/09/secret-to-rails-database-connection-pool-size which I think covers everything that needs to be said on this topic :)

We've also stopped observing `ActiveRecord::ConnectionTimeoutError` in GoodJob after I bumped the pool size, so we're all good. Thanks for the help!
