### ISSUE TITLE
not running jobs

### ISSUE THREAD

**Issue by nik736** [bensheldon/good_job#168]
Hello,

Thanks for this gem! I am kind of confused. Scenario: Production Environment. I am starting puma simply by typing:
`bundle exec puma -e production -d`

I am using:
`config.active_job.queue_adapter = :good_job`

From the docs I assume the execution_mode is set to external because of the production environment.

So far so good, the jobs are written to the database, but they are never executed. When I run:

`RAILS_ENV=production bundle exec good_job`

The jobs are not executed. How do I actually run them?

Thanks! :)

**Comment by bensheldon** [comment]
@nik736 thanks for opening an issue. I'm not quite sure what the problem is and am not able to reproduce it.

My initial thought is that `bundle exec puma -e production` doesn't set `Rails.env == 'production'` but from doing some poking it does seem like the environment is set correctly.

`RAILS_ENV=production bundle exec good_job` should run any jobs that are enqueued in in the `good_jobs` database table of the production database. It should check for jobs to execute every `GOOD_JOB_POLL_INTERVAL` which is 5 seconds by default.

If you can share more of your project, or make a demonstration repo I could maybe see if there is some configuration that is in the wrong place.
