### ISSUE TITLE
Allow job management (retry, destroy) through the Web UI

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#256]
Follow-up to #50  and reconsidered features by #255. Please share examples from other adapters.

**Comment by bensheldon** [comment]
Thank you @morgoth for jumping into #265 🙏 

I wanted to share some further thoughts/learnings from reviewing that:

- Conceptually, I think we need to be clearer through the UI that the `GoodJob::Job` object is an "ActiveJob Job Run/Execution". Making ActiveJob "Jobs" (AJob) and GoodJob "Jobs" (GJob) have a conceptual collision is something I regret.
- If you also implement "retries", I think that's something that needs to be acting on the ActiveJob Job to ensure that only the "head/latest" GJob is retried, to avoid having multiple executing GJobs for the same AJob. The retry operation will also need to be advisory locked, for the same reason. The latest PR #265 does have the risk of deleting a GJob that is currently executing, and would result in an error; I think the risk is low, but is something to clear up.

**Comment by jrochkind** [comment]
I'm imagining the use case for "retry through the Web UI" being for failed jobs.  By the time it gets to to good_job as a failure, ActiveJob has necessarily given up on it, yes?  So if "retry through the Web UI" is limited to failed jobs, is there less concern with collision like that?

I am interested in this feature! As far as "Please share examples from other adapters", here is what resque looks like. 

![Screen Shot 2021-07-15 at 11 19 20 AM](https://user-images.githubusercontent.com/149304/125813561-88167c3f-f2d5-4cf7-8ca8-c4096c3ed8e9.png)


There is a tab listing just "failed jobs".  There is a button to retry *all* jobs in list; or they can be retried individually. It somehow does keep track of whether a given job was already "retried" or not --which seems potentially tricky to do in good_job architecture?  The UI does _not_ keep track of whether the retry succeeded or not (that would be nice).  If the retry failed, it would show up a *second* time in the list, as a separate retried job. 

I don't actually love the UI, just here as an example. I do love the ability to manually retry jobs that are not otherwise going to be retried, ActiveJob/resque have given up on them.

**Comment by bensheldon** [comment]
Closing this because the core has been achieved. Please make additional requests/discussion in new Issues 👍
