### ISSUE TITLE
Pause jobs during migration / maintenance?

### ISSUE THREAD

**Issue by reczy** [bensheldon/good_job#257]
Is there (or could there be) a way to accomplish this globally via GoodJob? Historically, if not having running background jobs was a necessity, I'd put the website into maintenance mode and make sure all jobs finished. Is there a better way? Thanks!

**Comment by bensheldon** [comment]
My top-level recommendation would be to use [StrongMigrations](https://github.com/ankane/strong_migrations) and backward-code-compatible migrations so that you don't have to stop jobs or webservers at all.

Otherwise, the safest option would be to turn off all job processes and put the website into maintenance mode as you described..

Experimentally, you could put the website into maintenance mode (to prevent new jobs from being created) and invoke a query to lock all of the jobs (e.g. `GoodJob::Job.all.advisory_lock`) and just hold that lock until you're finished. But I think that's very experimental.

**Comment by reczy** [comment]
Thanks for your response - the strong migrations gem is a good suggestion.
