### ISSUE TITLE
Support for good_job without Rails?

### ISSUE THREAD

**Issue by stephanvd** [bensheldon/good_job#295]
Liking the look of good_job, thanks for this!

We are evaluating good_job for a Sinatra app that currently uses `Delayed::Job` through the `ActiveJob` interface. I have something working in dev for testing purposes by mocking a rails app with only `Rails.application.{config, executor}` defined and cofiguring good_job by env vars.

Any advise on this approach? Alternatively, given that the contact surface with Rails is pretty small (outside of generators which we won't be using) how would you feel about making `good_job` rails agnostic?

**Comment by bensheldon** [comment]
@stephanvd Unfortunately I'm not able to add support for non-Rails frameworks to GoodJob. I personally don't have the bandwidth to support it and there is a lot of Rails-specific footprint because there is reliance on Rails initialization, Rails multi-threading, ActiveJob, ActiveRecord, and ActiveSupport. GoodJob really is built _for_ Rails.
