### ISSUE TITLE
Content security policy for dashboard; nest shared view partials; problematic NOW() SQL in Dashboard query  

### ISSUE THREAD

**Issue by nsilva-ta** [bensheldon/good_job#304]
The browser refuses to open some parts of dashboard when the app has a content security policy:
```ruby
# config/initializers/content_security_policy.rb
Rails.application.config.content_security_policy do |policy|
  policy.default_src :none
  policy.connect_src :self
  policy.base_uri :none
  policy.font_src :self, :https, :data
  policy.img_src :self, :https, :data
  policy.object_src :none
  policy.script_src :self
  policy.style_src :self
  policy.form_action :self
  policy.frame_ancestors :self
end

Rails.application.config.content_security_policy_nonce_generator = ->(_request) { SecureRandom.base64(16) }
```

Also in the dashboard engine I have this doubts:

- I think the views shared folder should have a namespace 
good_job/engine/app/views/shaded/good_job or good_job/engine/app/views/good_job/shared

- In the index action of  DashboardsController use SQL with NOW() function. As dates came from Time.current and probably get converted to UTC when inserted in the database, i think that in some timezones the results period as an undesired offset.

**Comment by bensheldon** [comment]
Thanks for reporting the issues with CSP. I'll see if I can figure out what's going on.

And I agree with you about the Dashboard Engine doubts you raised. You're welcome to make a PR, or I'll get to it.

**Comment by bensheldon** [comment]
Actually, I think the times/timezones should be coming from the Rails side (rather than `NOW()`) but I'll doublecheck that they're being coerced correctly.

**Comment by bensheldon** [comment]
@aried3r Rails uses `timestamp without time zone` for its timestamp columns, therefore GoodJob does too. This is [expected to change in the next release of Rails](https://github.com/rails/rails/pull/41084). 

Replacing the `NOW()` is a simple compatibility fix that I can simply make a PR for, but I think the query could be better (e.g. rather than joining against a `generate_series`, doing a `group by date_trunc` and then using Ruby to walk over the resulting structure and fill in the empty values, and I'd like to reimagine the entire chart too (it's primarily a see-it-has-charts placeholder right now). I will open a separate Issue for that.
