### ISSUE TITLE
Concurrency's enqueue_limit should exclude performing jobs from count

### ISSUE THREAD

**Issue by vfonic** [bensheldon/good_job#317]
Hey Ben!

Thanks for the great gem! I just discovered it and it seems to be an improvement on top of DelayedJob which I'm using.

Currently, I have some custom duplication-prevention code that prevents adding a job with the same arguments to the queue if such job (with same arguments) already exists in the queue _and is not currently running_. (If a job with the same arguments is currently running, we allow adding a job to the queue.)

Is there any such solution for GoodJob? How would I go about adding support for this myself?

Thanks!

**Comment by bensheldon** [comment]
Yep! [GoodJob's ActiveJob Concurrency](https://github.com/bensheldon/good_job#activejob-concurrency) extension can do this with `enqueue_limit`. But it does not do the "and is not currently running" as `enqueue_limit` currently includes executing jobs. 

It's technically possible to exclude executing jobs. Could you make that argument? I'm open to changing it. 

If you wanted to monkeypatch your own use instead, chain in this line to include `.advisory_unlocked` scope:

https://github.com/bensheldon/good_job/blob/d365e3ef04f8580da40e65dc7c7e47feeb65e196/lib/good_job/active_job_extensions/concurrency.rb#L24

And then:

```ruby
class MyJob < ApplicationJob
  include GoodJob::ActiveJobExtensions::Concurrency

  good_job_control_concurrency_with enqueue_limit: 1, key: -> { "Unique-#{arguments.first}" }

  def perform(first_name)
    # do work
  end
end
```

FYI, You can test the resulting key that is generated this way (I should add this to the readme):

```ruby
job = MyJob.perform_later("Something")
job.good_job_concurrency_key #=> "Unique-Something"
```

**Comment by bensheldon** [comment]
By the way, I tried to follow the semantics of this thread upstream on Rails. I'd want to stay in alignment with that proposal, but I don't think they specified this: https://github.com/rails/rails/pull/40337

**Comment by bensheldon** [comment]
> This is a race condition.

That's a compelling reason.

And I remembered the reason why I initially counted executing jobs: retrying on errors. Example: job1 is executing, job2 is enqueued and the constraint of `enqueue_limit: 1` is preserved. If job1 errors and is attempted to be retried, it will hit the constraint that prevents it from being re-enqueued. In this situation, what should happen?

- job1 is re-enqueued, ignoring the constraint (2 matching jobs are now enqueued)
- do not re-enqueue job1. How to preserve/indicate _why_ when inspecting the job/Dashboard.

I lean towards the first case (re-enqueue and ignore the constraint), but I'm curious about your perspective.

**Comment by bensheldon** [comment]
FYI, I updated the Readme with additional keywords (duplicate, double) and the testing example 🎉

**Comment by vfonic** [comment]
If job1 errors, I'd assume it goes back to the end of the queue. So job2 will start executing before job1.

For "sync" purposes, it's important that at least one job starts after the record has been last saved.

There might be some other cases where it's better to try to remove the duplication. I'd argue that delivering the same message twice is better than skipping executing a job because there's "the same job" already running.

This is an edge-case where I'd probably go for simplicity: use the same code that is already there. If job1 errors, it would be the best if it would be removed, if job2 started running after job1 errored. But, for the sake of simplicity, I'd allow job1 to be added to the queue if the check for duplicates says there are no duplicates (job2 has the same arguments, but it's currently executing)

**Comment by bensheldon** [comment]
> There might be some other cases where it's better to try to remove the duplication. I'd argue that delivering the same message twice is better than skipping executing a job because there's "the same job" already running.

I agree with this. I think that's saying "running a job incompletely is more problematic than running a 2nd job with duplicate conditions."

To move forward, I'm thinking:

- change `enqueue_limit`'s count to exclude executing jobs
- allow the `enqueue_limit` constraint to be ignored when retrying jobs, which can lead to there being multiple enqueued jobs with the same conditions.
- Update the readme to note this, and recommend that if using an `enqueue_limit: 1` to also set `perform_limit: 1` to guard against a retried job executing at the same time as another job with duplicate conditions was enqueued.

**Comment by vfonic** [comment]
Sounds perfect! Thanks @bensheldon! :)

I'm curious to see what the rails team will do with their concurrency solution.

**Comment by codyrobbins** [comment]
When I first started playing around with the concurrency extension I was mildly surprised when I realized that `enqueue_limit` included performing jobs, but I don’t have a strong preference either way in terms of whether it should or not. I think you could make an argument for either option because you can achieve the same functionality either way, and the current behavior makes sense when you realize what’s going on, although excluding performing jobs has the advantage of avoiding violating the principle of least surprise.

For our use case we are running jobs that sync user data against external APIs in response to webhooks. We wanted to ensure that only one instance of the same sync job is ever running at the same time to avoid multiple simultaneous syncs interfering with each other and so we have `perform_limit` set to 1. If a change happens in the midst of an already running sync, though, we want to run another sync immediately after the first one completes in order to pick up those new changes. If multiple changes occur during a running sync, though, we never need to enqueue more than one additional sync job because that one sync job will pick up all subsequent changes when it runs after the current one. So, we have `enqueue_limit` set to 2.

This effectively serves as a kind of debounce on the trailing edge, since it ensures that we always pick up new changes when they happen without running multiple unnecessary syncs, but it doesn’t function across a time window. I can imagine that in the future with heavier load we may need a time-based throttle like that discussed in #315, though.
