### ISSUE TITLE
Allow "mass"-actions through Dashboard (e.g. retry all)

### ISSUE THREAD

**Issue by bensheldon** [bensheldon/good_job#446]
Follow-up to #256 

Add checkboxes to each of the rows, and form buttons that will apply an action (e.g. Retry, Discard, etc.) to all of the checked boxes.

Check-all logic is a bit magical to me, because there is both:
- Check all of the boxes on this screen
- Apply to everything that exists 

e.g. how GMail does it: 

<img width="652" alt="Screen Shot 2021-11-04 at 8 24 21 AM" src="https://user-images.githubusercontent.com/47554/140352079-7c6a523d-dea8-4e2e-8c10-15914c3309bf.png">

I think for this case, having two checkboxes, one of which is a multicheckbox "Select All" and the other is "Select everything" is fine or whatever uses the least amount of javascript. ... or just defer the "Select everything".

**Comment by jrochkind** [comment]
Seems right! I think the "select everything, not just what's on this page" is a real use case. (I _think_ resque admin did _not_ give this to me, though -- and I often wanted it!)

**Comment by bensheldon** [comment]
An open question/fear will be how many Jobs can be acted upon before the request times out. Some actions can be done with a single UPDATE statement (Discard, Reschedule), but some of them require INSERTS (Re-enqueue).  Trying to do it in a single (or at least not N) database operation would also require taking multiple advisory locks at once. A fun challenge.

**Comment by reczy** [comment]
@bensheldon would it make sense to perform those complex/bulk actions in a built-in background job (or jobs) that you ship with GoodJob?

**Comment by bensheldon** [comment]
@reczy I'm reluctant to have jobs emanating from GoodJob, but try to change my mind. (this was also suggested in #412)

Conceptually, I think of jobs as living in application-land. GoodJob runs jobs, but jobs come from the application, not vice-versa. 

Configurationally, I think it gets complicated. 

- Ensuring the adapter is GoodJob (though maybe it doesn't have to be)
- Configuring what the base-class is for the job (because that might have configuration)
- Ensuring that the job is enqueued on a queue that has executors
- If the queue is `default`, should it be low or high priority, because that might effect the quality of service of other jobs emanating from the application.

These aren't insurmountable by any means, but complicated.

**Comment by reczy** [comment]
I think the strongest argument I can come up with to "change your mind" is that, as a GoodJob user, I would rather have a little more thought-overhead / extra step on setup than face a situation where I can't perform bulk actions because of repeated timeouts, presumably (or at least possibly) at a time when something has gone wrong or I'd like to act quickly. I guess another argument would be that if a user was building this on their own in their own application, I think the more likely recommendation would be to do so in a job rather than a web request.

I hadn't considered all your configuration challenges, though some thoughts are:

- My initial instinct would be to give highest priority to an action that was manually performed in the dashboard and lowest priority to any jobs that GoodJob would enqueue on its own behind the scenes.
- What timeout time do you actually test against here to see if this is even necessary? Do you conservatively pick a timeout like 10s or maybe something a little more forgiving like 30s? - I would probably argue for something closer to the former.

While I'm not specifically advocating that a job _should_ be used here, I suppose conceptually, as a _user_ of GoodJob, I am indifferent as to whether the the gem has its own builtin jobs. If using a job vs a web request solves a real problem or makes the gem better, I'm all for it.

**Comment by bensheldon** [comment]
@reczy we're in total agreement 👍  If it comes to a situation in which GoodJob enqueuing its own jobs is the only reliable way to implement a feature reliably, then it's under consideration.

I'm thinking 30s is the upper bound of an unacceptable http request duration.
