### ISSUE TITLE
Assets not loaded when Rails is configured with a different hostname for assets

### ISSUE THREAD

**Issue by vitobotta** [bensheldon/good_job#491]
Hi! Awesome job with... Good Job :D

I have configured my app to use a different hostname for assets, which is a CDN hostname. Assets for the Good Job UI cannot be loaded from this hostname for some reason, while they load from the main hostname of the app. Any suggestions on how to fix? Thanks!

**Comment by bensheldon** [comment]
Hi @vitobotta, thanks for opening an issue! This is an interesting area 😄 

GoodJob's CSS/JS assets do not go through Rails' asset pipeline; they're served as regular routes/controllers/"views" of the GoodJob Engine. The reason for this was that Rails has too many competing pipeline configurations right now for me to reasonably be compatible with (it seems fairly common for gem/Engines to either take my strategy or to inline the assets in the header of every page request).

Just to clarify for me the issue, is it?:

- The GoodJob Dashboard doesn't display properly because the assets aren't being served at all. _This is interesting and unexpected. I'm curious if you could share a screenshot of your browser's Network Panel that shows where these requests are being routed. I might also wonder if it's a CSP problem_
- You expected the assets to be served from the CDN, and they're not, but the Dashboard displays fine. _In this case, GoodJob is working as intended._

**Comment by vitobotta** [comment]
Hi @bensheldon :)

See picture https://cln.sh/lyjiaZ

So it tries to serve the assets from the cdn hostname (cdn.domain.com) like all the other assets, but they all return 404 for Good Job assets. If I just change the hostname of the asset urls to app.domain.com, which is the main hostname of the app, the assets load just fine. I don't get any CORS related errors, just 404s when the assets are served from the cdn hostname. Any ideas?

**Comment by bensheldon** [comment]
@vitobotta aha! I see now. `stylesheet_link_tag` and `javascript_include_tag` are rewriting the GoodJob asset paths to include the hostname from `config.asset_host`. I can fix that.

**Comment by bensheldon** [comment]
Released in [`v2.9.3`](https://github.com/bensheldon/good_job/releases/tag/v2.9.3) 🎉

**Comment by vitobotta** [comment]
That's awesome, it works like a charm. Thanks for doing this so quickly! Love the gem ❤️
