### ISSUE TITLE
Not all loggers have a formatter

### ISSUE THREAD

**Issue by adibsaad** [bensheldon/good_job#502]
https://github.com/bensheldon/good_job/blob/2bb47821963f374d122d9d2384193535ae318195/lib/good_job/log_subscriber.rb#L198

`each_logger.formatter` can be nil

Issue mentioned in https://github.com/reidmorrison/rails_semantic_logger/issues/29

**Comment by bensheldon** [comment]
Thanks for the heads up! That can be feature-tested for in GoodJob. 

Looks like tagged logging might also be a problem too.

**Comment by adibsaad** [comment]
Thanks for the quick response.

Another observation: using the fix I put in that issue, GoodJob starts logging twice, once with its own logger (I'm guessing) and one with Rails.logger

```
[GoodJob] [88944] GoodJob started scheduler with queues=* max_threads=5.
2022-01-29 18:44:39.517917 I [88944:63220] [GoodJob] [88944] Rails -- GoodJob started scheduler with queues=* max_threads=5.
[GoodJob] GoodJob started cron with 2 jobs.
2022-01-29 18:44:39.954994 I [88944:63220] [GoodJob] Rails -- GoodJob started cron with 2 jobs.
[GoodJob] Notifier subscribed with LISTEN
2022-01-29 18:44:40.078149 I [88944:GoodJob::Notifier-worker-1] [GoodJob] Rails -- Notifier subscribed with LISTEN
```

**Comment by bensheldon** [comment]
Looking at this now. My assumption was that any logger that is a tagged logger would have a populated formatter. I can guard against that being nil too.

https://github.com/bensheldon/good_job/blob/2bb47821963f374d122d9d2384193535ae318195/lib/good_job/log_subscriber.rb#L197-L198

Also, I was curious why GoodJob has this problem because I borrowed the log tagging structure from ActiveJob. Looks like SemanticLogger monkey patches Rails:

https://github.com/reidmorrison/rails_semantic_logger/blob/e83a306296670f205aa6adae9017528d22a8191c/lib/rails_semantic_logger/extensions/active_job/logging.rb
