### ISSUE TITLE
Cron Schedule jobs add disable action

### ISSUE THREAD

**Issue by Sylor-huang** [bensheldon/good_job#540]
Hi and thanks for this awesome gem!

My good_job version is `2.11.2`.

I used to use the Sidekiq，and sidekiq has these functions in recurring jobs: `Enqueue Now` and `Disable`

It's very useful for my work.

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/26167245/157574884-cb54ea6f-080f-4806-a214-bede484a04c1.png">

But with good_job, it seems only has the `Enqueue Now` function,  **is there any plans to add `disable` action to schedule jobs?**

<img width="618" alt="image" src="https://user-images.githubusercontent.com/26167245/157575061-94f0efad-75ff-47fe-883a-381b0d20dcaf.png">

Thanks.

**Comment by bensheldon** [comment]
@Sylor-huang thanks for the suggestion! I'm curious: could you tell me a bit more about how you use the "Disable" feature? e.g. under what circumstances do you disable a cron run, and then disable it later? What are the ops/business reasons?

I do think that would be a great feature to add. It makes me think that there is an implementation challenge because disabling an entry would require storing that configuration in the database and I'd want to think through how to do that in a lighweightly extensible way (e.g. maybe a `good_job_settings` table in the database with a unique key/namespace and a jsonb value to store the data).

**Comment by Sylor-huang** [comment]
@bensheldon  Thanks for your reply, I'm looking forward to adding the `disable` feature.

Our datas saved in redshift database. 
Every Monday, our operations staff will maintain these tables，and at the same time, they should disable the jobs，
prevent writing data to these tables。

Thanks.
