### ISSUE TITLE
Good job is using a lot of memory / ram

### ISSUE THREAD

**Issue by rgaufman** [bensheldon/good_job#613]
Hi there,

I have my good_job set up like this:

```
    config.good_job = {
      preserve_job_records: false,
      retry_on_unhandled_error: false,
      on_thread_error: ->(exception) { Airbrake.notify(exception) },
      execution_mode: :external,
      queues: '*',
      max_threads: 10,
      poll_interval: 15,
      shutdown_timeout: 25,
      enable_cron: true,
      logger: Rails.logger
    }
```

Here is a screenshot of it in action:

<img width="1527" alt="Screenshot 2022-05-29 at 20 01 51" src="https://user-images.githubusercontent.com/33842342/170887276-7b464d7c-fc07-461b-930f-275b4ab37fc9.png">

There are rarely more than 3-4 jobs running in parallel.

Compared to Sidekiq running the same jobs, it seems to take almost double the ram and looks like this in top:
<img width="970" alt="Screenshot 2022-05-29 at 20 02 55" src="https://user-images.githubusercontent.com/33842342/170887343-cdeb9c33-798d-458b-b9f7-469096f71e8d.png">

Any ideas what could be responsible for this? - maybe I should disable the dashboard? - How would I troubleshoot and reduce ram usage?

**Comment by rgaufman** [comment]
I noticed strange behaviour, when starting puma and good_job, both jump to 30% ram use. Then Puma starts to drop quite quickly and ends at around 10-13%. Good_job stays at around 30% - this is 5 minutes later:

<img width="889" alt="Screenshot 2022-05-29 at 20 33 36" src="https://user-images.githubusercontent.com/33842342/170888400-e297fbfc-0ed7-4860-ab92-7089c49a3964.png">

(This is with the dashboard disabled and preserve_job_records: false)

**Comment by bensheldon** [comment]
@rgaufman thanks for sharing this! I haven't done much memory profiling of GoodJob, though I'm surprised that GoodJob would perform significantly differently than Puma. Take the following as speculation (because I haven't looked)...

GoodJob's initialization process is pretty simple:

1. Boots the Rails framework: https://github.com/bensheldon/good_job/blob/8b4fc67f0f78d3338c5df8e13851935ee6ca4812/lib/good_job/cli.rb#L158-L159
2. Initializes a bunch of Concurrent Ruby objects (ThreadExecutors, Timers): https://github.com/bensheldon/good_job/blob/8b4fc67f0f78d3338c5df8e13851935ee6ca4812/lib/good_job/cli.rb#L92-L99
3. Queries for existing and future jobs to cache <-- this is a potential culprit, but when I [built the feature](https://github.com/bensheldon/good_job/pull/205) I saw it use ~20MB/10k cached items.
4. Anytime that an execution thread is awakened (e.g. to execute a job immediately over LISTEN/NOTIFY, a scheduled job from the cache, or every poll_interval) that thread takes place inside a [Rails Executor](https://guides.rubyonrails.org/threading_and_code_execution.html#wrapping-application-code) which should be similar to how Puma works. One thing to flag here is that the `poll_interval` wakes up a thread and make an ActiveRecord query every N seconds.

Because I haven't done any memory profiling, I can't give you anything specific about how to dig into the problem. I think trying to get some stackprof points into the initialization would be a good place to start, and look at allocated objects. It sounds like there isn't a problem though with object retention (e.g. memory usage increases over time), just that there is more than expected in the first place.

BTW, here's memory usage for my [reference application](https://dayoftheshirt.com).

- Web: Puma with web concurrency 1, rails max threads 5:
    <img width="1226" alt="Screen Shot 2022-05-30 at 7 53 32 AM" src="https://user-images.githubusercontent.com/47554/171025101-570a2df0-8f81-442f-93c0-9fac5ee4bc39.png">
- Worker: GoodJob with 4 threads (good job queues = `-newsletters:2;newsletters:2`)
    
<img width="1234" alt="Screen Shot 2022-05-30 at 7 53 41 AM" src="https://user-images.githubusercontent.com/47554/171025121-2e481b81-fcb0-40c6-8dc0-68f5f2ffadb0.png">

**Comment by sedubois** [comment]
Since upgrading our app from GoodJob 2.15.1 to 3.0.0 our Heroku worker memory is spiking, whereas the web dyno memory usage hasn't changed.

<img width="1587" alt="Screenshot 2022-07-02 at 12 56 15" src="https://user-images.githubusercontent.com/4217871/176997836-97f5722f-d710-41df-b262-71997e99af71.png">

We also upgraded other dependencies in this release (e.g Zeitwerk, rack, ...), but for some reason the first suspect that comes to mind is GoodJob, as it's the worker memory which has increased.

Here is the GoodJob initializer, for reference (in this release we also changed the syntax from `GoodJob.X = Y` into `Rails.application.configure do ... end`):

<details>

```rb
# app/config/good_job.rb

Rails.application.configure do
  config.good_job.preserve_job_records = true
  config.good_job.retry_on_unhandled_error = false
  config.good_job.on_thread_error = -> (exception) do
    Sentry.set_extras(good_job_on_thread_error: true)
    Sentry.capture_exception(exception)
  end
end

ActionMailer::MailDeliveryJob.retry_on StandardError,
                                       wait: :exponentially_longer, attempts: Float::INFINITY
ActionMailer::MailDeliveryJob.around_perform do |_job, block|
  block.call
rescue StandardError => e
  Sentry.set_extras(action_mailer_standard_error: true)
  Sentry.capture_exception(e)
  raise
end
```

</details>

The app has very few jobs (one job every few minutes ATM) and these typically shouldn't use much memory as they either send some emails or make some API calls.

Any idea if/how GoodJob could cause this?

**Comment by bensheldon** [comment]
@sedubois yikes! That's not good. 

I can't think of anything off the top of my head that would have blown out memory. 

Looking through the Changelog, the major changes are:

- converting GoodJob to a singular engine. I don't think this would vastly effect memory, though it does mean a few more controllers might be eager-loaded into memory at boot. 
- Zeitwerk configuration changes. Can't imagine anything here changing significantly unless Zeitwerk itself was doing something very unexpected, and i wouldn't expect that. 
- Automatically deleting old jobs was a feature changed to default enabled in GoodJob 3.0. Every 10 minutes it deletes old jobs. I think this could be the culprit, but I tried to do as much work as possible in the database rather than the app.


Let me do another sweep through the code and see what I can find.

**Comment by bensheldon** [comment]
@sedubois I found a possible culprit in #652 which has been released in v3.0.1. Please give that a try and let me know if that fixes your problems.

**Comment by sedubois** [comment]
@bensheldon yesterday I downgraded GoodJob from 3.0.0 to 2.15.1 and the memory issue had disappeared. Today I upgraded to 3.0.1 and there have also not been any memory spikes since. So it seems solved, thanks! 👍

**Comment by bensheldon** [comment]
@sedubois fantastic! 🎉
