### ISSUE TITLE
Provide example how to store exception messages in db

### ISSUE THREAD

**Issue by lauer** [bensheldon/good_job#63]
I have implemented ActiveJob/GoodJob on some external API calls, which provide a 400 Bad request and a json error message if something is wrong with the request (e.g validation errors)

Currently, our application returns an exception ApiError.new(status: e.status, result: e.result).
However, currently only the new of this error Call is stored in the database, and not the full error message.

Could you provide some documentation, how to store this error, or maybe implement it as a feature. 

If I use `MyJob.perfom_now(<args)` I do get the error message correctly.

**Comment by bensheldon** [comment]
Thanks for giving GoodJob a shot!

The responsibility of the `good_jobs` table is for scheduling upcoming jobs. The `good_jobs` table does contain an `error` column, but there are a lot of reasons why it might not be populated because it only captures errors that bubble up all the way to the GoodJob backend, and if ActiveJob is configured safely/recommended, exceptions bubbling up to the GoodJob backend would be truly exceptional. 

This is how the error is serialized into the `good_jobs.error` column, which (**Feature**) could be turned into a configurable lambda that exposes the error and allows the application to format the string that is stored in the database:

https://github.com/bensheldon/good_job/blob/c254589c06ff1c090bf29f89ac391ee886f3e441/lib/good_job/job.rb#L89-L90


But! ...

If you do need to store or inspect specific errors, I would highly recommend instead:

- Using an exception monitoring service like Sentry, Bugsnag, Airbrake, etc.
- Logging out the exception
- If the goal is integrity/book-keeping, storing a ~`successfully_told_api_at` column on the business resource itself and not the job resource (or the opposite ~`failed_validation_because`)

In code this is how I would structure it. Some of it might better live in `ApplicationJob` but to show all the parts:

```ruby
class ApiRequestJob < ApplicationJob 
  # Always retry all errors
  retry_on StandardError, wait: :exponentially_longer, attempts: Float::INFINITY

  around_perform do |block|
    begin
      block.call
    rescue ApiError => api_error
      # <= Send to Sentry/Airbrake/etc or log the error
      raise
    end
  end

  def perform(your_args)
    begin
      # make api request(s)
    rescue => e
      # <= if you go the integrity/book-keeping route, store the  `failed_validation_because` column here
      raise ApiError.new(status: e.status, result: e.result), "Api request failed"
    end

    # <= if you go the integrity/book-keeping route, touch the `successfully_told_api_at` column here
  end
end 
```

**Comment by lauer** [comment]
Thanks for your time. I figured a missing message access in the ApiError exception. So now I get the logged message inside the good_job table. 

We are using Sentry, and it seems the errors already are sent to this service. However we somehow need to provide the error to the user of our API. 
I can't decide if we should create an API resource for the jobs database when the client know the job_id, or we should provide a possibility for the client, to receive status through a callback url.

**Comment by bensheldon** [comment]
@lauer it sounds like my curiosity is beyond the scope of GoodJob, but I'm curious about this:

> I can't decide if we should create an API resource for the jobs database when the client know the job_id, or we should provide a possibility for the client, to receive status through a callback url.

I recommend against tying your implementation to the jobs table because it's optimized for running jobs. I would recommend instead creating a resource within your application that models the lifecycle of this API call; that will give you much more control and flexibility... and also make me less worried as a gem maintainer that a change to the GoodJob internal implementation will have wide-reaching effects in your application.

And FYI, the GoodJob job_id will change if the job's `ActiveJob.retry_on` is triggered. The durable id is ActiveJob ID, which is serialized inside of the `good_jobs.serialized_params` jsonb column.
