### ISSUE TITLE
How to accomplish user controlled recurring jobs?

### ISSUE THREAD

**Issue by mraffonso** [bensheldon/good_job#640]
I have an app where users can schedule various tasks to be executed daily or weekly at a time of their choosing.

Currently I'm using delayed_cron_job to accomplish this because
* It's easy to create recurring jobs on the fly
* They are easy to remove (just deleting a record from the database)
* Recurring jobs are persisted in the database and will surive reboot and updates

In the docs the only way I see to handle recurring jobs is to hardcode them and redeploy the application.

Is there a way to acheive something similar with GoodJob?

**Comment by bensheldon** [comment]
GoodJob's cron function is designed from an ops perspective, so unfortunately it requires changing static configuration. I'd also recommend, generally, trying to keep your queue as constrained as possible (e.g. don't enqueue tons of scheduled jobs; don't use the queue as a business record) so that the queue can focus on performant throughput.

If you wanted to move to GoodJob, I'd recommend that you build this functionality into your application. e.g.:

- Write the cron configuration to your own model, associated with the user, with any other metadata you want to include
- Use GoodJob cron to check every n-minutes for any of your cron models that would have triggered during the last time period, and then enqueue the action associated with it.

**Comment by mraffonso** [comment]
Thanks @bensheldon for explaining why its designed that way and how to best leverage it.  Your recomendation on how to implement is basically what I was anticipating if I were to switch to GoodJob on this project, so that does make me feel a bit more confident in changing how we handle scheduled jobs.

I will close this issue as I don't think my question can be answered any further.
