### ISSUE TITLE
Minor Cron Concurrency Clarification

### ISSUE THREAD

**Issue by jonahgeorge** [bensheldon/good_job#743]
Based on https://github.com/bensheldon/good_job/issues/690, I'm under the impression it's entirely safe to run multiple workers with cron enabled. You would just suffer a slightly higher resource utilization. Is this actually the case?

If so, would you accept a minor README update to clarify this? I originally assumed this but doubted myself when I saw the snippet below without any other explanation:

```rb
# Enable cron in this process; e.g. only run on the first Heroku worker process
config.good_job.enable_cron = ENV['DYNO'] == 'worker.1' # or `true` or via $GOOD_JOB_ENABLE_CRON
```

Thanks a ton for your work on this project!

**Comment by bensheldon** [comment]
@jonahgeorge yep! it is safe to run multiple workers with cron enabled....by default, as long job records are preserved because a unique index is used on the cron key+time in the database and if the record is deleted and there is enough clock-drift another process could re-enqueue with the same key+time. But that is probably a rare risk.

That snippet could use some explanation, or you could remove it entirely.

**Comment by jonahgeorge** [comment]
Awesome, thanks!
