### ISSUE TITLE
GoodJob has pending database migrations after v2 -> v3 

### ISSUE THREAD

**Issue by stephenhuey** [bensheldon/good_job#920]
Just upgraded from 2.15.1 to 2.99.0 and ran `rails g good_job:update` and `rails db:migrate` and then changed Gemfile to 3.15.0 but the **Batches** view tells me "GoodJob has pending database migrations."  Not sure I need the Batches view right now so I might not be too worried.  :)

**Comment by bensheldon** [comment]
@stephenhuey thanks for opening this issue! I think everything is working as intended, but always good to doublecheck 😄 

Batches were introduced in `v3.10.0`. The migration message would be because you upgraded past that version from `v2.99` to `v3.15.0`. No problem, you can run `rails g good_job:update`

My interpretation of semver for GoodJob is that if a new feature requires a database migration, I'll leave the migration optional (and show that "pending database migrations") message until the next major release.

**Comment by stephenhuey** [comment]
Much obliged @bensheldon!  I didn't think to run update again.  But nice to know it was optional--I think your interpretation makes sense.  :)
