### ISSUE TITLE
config.good_job.preserve_job_records = false not working with CRON

### ISSUE THREAD

**Issue by ollym** [bensheldon/good_job#927]
When good_job runs a cron job its preserved in state `finished` even though we have `preserve_job_records = false`

**Comment by bensheldon** [comment]
This is intentional. Cron uses a unique index on `(cron_key, cron_at)` columns. That requires keeping the record around, otherwise it's possible that multiple jobs could be enqueued if the record is immediately deleted after running.

It's not ideal, but necessary for how cron currently works. 

There's more detail in #767 / #731
